### ISSUE TITLE
購入したスタンプはエラーになる

### ISSUE THREAD

**Issue by mursts** [mursts/linebot-py#1]
```
{"statusCode":"542","statusMessage":"BOT_INVALID_PARAMETER"}
Exception on /bot/callback [POST]
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 62, in callback
    r.raise_for_status()
  File "/app/.heroku/python/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trialbot-api.line.me/v1/events
```

**Comment by mursts** [comment]
そもそも有料スタンプは仕様で送れなさそう

**Comment by raooll** [comment]
how did you fix this issue ? @mursts

**Comment by mursts** [comment]
@raooll sorry.. I won't fix this issue. Maybe this is the specifications.
I thins can't send paid stamp.

**Comment by raooll** [comment]
@mursts what causes this error ?

**Comment by mursts** [comment]
@raooll sorry. I don't know this
